// SPDX-License-Identifier: GPL-3.0-only
//
// Crystal Grotto is based on Crystal Palace.
// Copyright 2025 Raphael Mudge, Adversary Fan Fiction Writers Guild.

// Package grotto parses and executes Crystal Palace-compatible linker
// specifications.
package grotto

import (
	"os"

	"github.com/sliverarmory/crystal-grotto/internal/engine"
	"github.com/sliverarmory/crystal-grotto/internal/spec"
)

const (
	// Version is the Crystal Grotto application version.
	Version = "0.1.0"
	// CompatibilityBaseline identifies the pinned upstream source distribution.
	CompatibilityBaseline = "2026-07-16"
	// UpstreamVersion is the version string reported by that distribution.
	UpstreamVersion = "06.29.26"
)

type (
	// Metadata describes a specification.
	Metadata = spec.Metadata
	// ParseError aggregates syntax diagnostics.
	ParseError = spec.ParseError
	// ProgramError contains execution context for a runtime failure.
	ProgramError = spec.ProgramError
	// Capability identifies a DLL, COFF object, or build-only architecture.
	Capability = spec.Capability
	// Environment holds byte ($) and string (%) variables.
	Environment = spec.Environment
	// RunOptions customize one independent execution.
	RunOptions = spec.RunOptions
	// Result contains the linked program and optional generated rules.
	Result = spec.Result
	// Logger receives messages emitted by a spec.
	Logger = spec.Logger
	// LoggerFunc adapts a function to Logger.
	LoggerFunc = spec.LoggerFunc
	// Message is an echo or warning emitted by a spec.
	Message = spec.Message
	// MessageType classifies messages emitted by a spec.
	MessageType = spec.MessageType
	// StackValue is a typed linker VM value.
	StackValue = spec.StackValue
	// CommandHandler implements object/linker commands outside the core VM.
	CommandHandler = spec.CommandHandler
	// RuleProvider exposes rules generated by a command handler.
	RuleProvider = spec.RuleProvider
	// RuleGenerationRequester receives the RunAndGenerate execution signal.
	RuleGenerationRequester = spec.RuleGenerationRequester
	// ExecutionContext exposes controlled VM state to a command handler.
	ExecutionContext = spec.ExecutionContext
	// Command is one parsed spec-language command.
	Command = spec.Command
)

// Spec is a parsed, reusable linker specification. Public executions install
// a fresh Crystal Grotto command handler when RunOptions.Handler is nil.
type Spec struct {
	program *spec.Spec
}

const (
	MessageEcho    = spec.MessageEcho
	MessageWarning = spec.MessageWarning
)

// Parse parses a Crystal Palace-compatible specification.
func Parse(file, content string) (*Spec, error) {
	program, err := spec.Parse(file, content)
	if err != nil {
		return nil, err
	}
	return &Spec{program: program}, nil
}

// ParseFile reads and parses a specification from disk.
func ParseFile(path string) (*Spec, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return Parse(path, string(content))
}

// File returns the filename associated with this specification.
func (s *Spec) File() string { return s.program.File() }

// Metadata returns a copy of the specification metadata.
func (s *Spec) Metadata() Metadata { return s.program.Metadata() }

// Name returns explicitly configured metadata or a filename-derived name.
func (s *Spec) Name() string { return s.program.Name() }

// Targets reports whether a non-empty program exists for label.
func (s *Spec) Targets(label string) bool { return s.program.Targets(label) }

// Labels returns defined labels in stable order.
func (s *Spec) Labels() []string { return s.program.Labels() }

// Run executes a specification. A nil Handler selects a new request-local
// Crystal Grotto engine; an explicitly supplied Handler is preserved.
func (s *Spec) Run(capability Capability, options RunOptions) ([]byte, error) {
	return s.program.Run(capability, withDefaultHandler(options))
}

// RunAndGenerate executes a specification and returns program and rule output.
func (s *Spec) RunAndGenerate(capability Capability, options RunOptions) (Result, error) {
	return s.program.RunAndGenerate(capability, withDefaultHandler(options))
}

// RunConfig executes a configuration specification and requires an empty
// stack. Object commands use the same default-engine rule as Run.
func (s *Spec) RunConfig(capability Capability, options RunOptions) (Environment, error) {
	return s.program.RunConfig(capability, withDefaultHandler(options))
}

// NewCommandHandler constructs the default request-local object/linker engine.
// Most callers can leave RunOptions.Handler nil instead.
func NewCommandHandler() CommandHandler { return engine.New() }

func withDefaultHandler(options RunOptions) RunOptions {
	if options.Handler == nil {
		options.Handler = NewCommandHandler()
	}
	return options
}

// None creates a build-only capability for x86, x64, or a named target label.
func None(archOrLabel string) (Capability, error) { return spec.None(archOrLabel) }

// ParseCapability detects a PE DLL or COFF object capability.
func ParseCapability(data []byte) (Capability, error) { return spec.ParseCapability(data) }

// ParseObject creates a capability from COFF object bytes.
func ParseObject(data []byte) (Capability, error) { return spec.ParseObject(data) }

// ParseDLL creates a capability from PE DLL bytes.
func ParseDLL(data []byte) (Capability, error) { return spec.ParseDLL(data) }

// ParseCommand parses one spec-language command.
func ParseCommand(text string) *Command { return spec.ParseCommand(text) }
