// SPDX-License-Identifier: GPL-3.0-only

package regdance

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"io"
	"reflect"
	"sync"
	"testing"

	"github.com/sliverarmory/crystal-grotto/internal/coff"
)

func TestApplyDirectUpstreamVectors(t *testing.T) {
	// These exact .text vectors were generated by the unmodified upstream
	// RegDance/SavedRegContext/Rebuilder pipeline with Iced 1.21.0 after
	// replacing java.util.Collections.r with new java.util.Random(123).
	seed := int64(123)
	tests := []struct {
		name        string
		machine     coff.Machine
		input       []byte
		want        []byte
		wantMapping []Mapping
		wantChanged int
	}{
		{
			name:    "x86",
			machine: coff.MachineI386,
			input: []byte{
				0x55, 0x53, 0x56, 0x57,
				0x89, 0xf3,
				0x8d, 0x7c, 0x5d, 0x10,
				0x01, 0xfe,
				0x5f, 0x5e, 0x5b, 0x5d, 0xc3, 0x90, 0x90, 0x90,
			},
			want: []byte{
				0x55, 0x53, 0x56, 0x57,
				0x89, 0xfb,
				0x8d, 0x74, 0x5d, 0x10,
				0x01, 0xf7,
				0x5f, 0x5e, 0x5b, 0x5d, 0xc3, 0x90, 0x90, 0x90,
			},
			wantMapping: []Mapping{{RBP, RBP}, {RBX, RBX}, {RDI, RSI}, {RSI, RDI}},
			wantChanged: 3,
		},
		{
			name:    "x64 REX SIB and forced displacement",
			machine: coff.MachineAMD64,
			input: []byte{
				0x55, 0x53, 0x56, 0x57, 0x41, 0x54, 0x41, 0x55,
				0x48, 0x89, 0xf3,
				0x49, 0x89, 0xfc,
				0x4c, 0x8d, 0x6c, 0x5d, 0x10,
				0x88, 0x1e,
				0x41, 0x5d, 0x41, 0x5c, 0x5f, 0x5e, 0x5b, 0x5d, 0xc3, 0x90, 0x90,
			},
			want: []byte{
				0x55, 0x53, 0x56, 0x57, 0x41, 0x54, 0x41, 0x55,
				0x4d, 0x89, 0xec,
				0x48, 0x89, 0xfd,
				0x4a, 0x8d, 0x74, 0x63, 0x10,
				0x45, 0x88, 0x65, 0x00,
				0x41, 0x5d, 0x41, 0x5c, 0x5f, 0x5e, 0x5b, 0x5d, 0xc3, 0x90, 0x90,
			},
			wantMapping: []Mapping{{RBP, RBX}, {RBX, R12}, {R13, RSI}, {RDI, RDI}, {R12, RBP}, {RSI, R13}},
			wantChanged: 4,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			object, text, _ := fixture(t, test.machine, test.input, functionSpec{"go", 0})
			report, err := Apply(context.Background(), object, Options{Seed: &seed})
			if err != nil {
				t.Fatalf("Apply: %v", err)
			}
			if !bytes.Equal(text.Data, test.want) {
				t.Fatalf(".text = %x\nwant    %x", text.Data, test.want)
			}
			if report.EligibleFunctions != 1 || report.RemappedFunctions != 1 || report.ChangedInstructions != test.wantChanged || report.RandomDraws != len(test.wantMapping)-1 {
				t.Fatalf("report = %#v", report)
			}
			if len(report.Functions) != 1 || !reflect.DeepEqual(report.Functions[0].Mapping, test.wantMapping) || report.Functions[0].ChangedInstructions != test.wantChanged {
				t.Fatalf("function report = %#v", report.Functions)
			}
		})
	}
}

func TestApplyEligibilityAndExclusions(t *testing.T) {
	seed := int64(123)
	tests := []struct {
		name    string
		machine coff.Machine
		code    []byte
		wantMap int
	}{
		{name: "fewer than three distinct saved", machine: coff.MachineI386, code: []byte{0x55, 0x53, 0x89, 0xeb, 0x5b, 0x5d, 0xc3}},
		{name: "push pop count mismatch", machine: coff.MachineI386, code: []byte{0x55, 0x53, 0x56, 0x89, 0xeb, 0x5e, 0x5d, 0xc3}},
		{name: "multiple returns", machine: coff.MachineI386, code: []byte{0x55, 0x53, 0x56, 0x57, 0x90, 0x5f, 0x5e, 0x5b, 0x5d, 0xc3, 0xc3}},
		{name: "string excludes RSI and RDI", machine: coff.MachineI386, code: []byte{0x55, 0x53, 0x56, 0x57, 0xa5, 0x5f, 0x5e, 0x5b, 0x5d, 0xc3}},
		{name: "x86 BL excludes only RBX and leaves three", machine: coff.MachineI386, code: []byte{0x55, 0x53, 0x56, 0x57, 0x88, 0xd8, 0x89, 0xf7, 0x5f, 0x5e, 0x5b, 0x5d, 0xc3}, wantMap: 1},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			object, text, _ := fixture(t, test.machine, test.code, functionSpec{"go", 0})
			before := append([]byte(nil), text.Data...)
			report, err := Apply(context.Background(), object, Options{Seed: &seed})
			if err != nil {
				t.Fatalf("Apply: %v", err)
			}
			if report.RemappedFunctions != test.wantMap {
				t.Fatalf("report = %#v", report)
			}
			if test.wantMap == 0 && !bytes.Equal(text.Data, before) {
				t.Fatalf("ineligible function changed: %x -> %x", before, text.Data)
			}
			if test.wantMap == 1 {
				for _, mapping := range report.Functions[0].Mapping {
					if mapping.From == RBX {
						t.Fatalf("excluded RBX appears in mapping %#v", report.Functions[0].Mapping)
					}
				}
			}
		})
	}
}

func TestApplyUnsupportedIsTransactional(t *testing.T) {
	// vmovups ymm0,[rdi] needs an architectural VEX operand description that
	// go-capstone v0.0.1 does not expose. The eligible function must fail rather
	// than silently leaving RBX unpermuted.
	code := []byte{
		0x55, 0x53, 0x56, 0x57,
		0xc5, 0xfc, 0x10, 0x07,
		0x89, 0xf3,
		0x5f, 0x5e, 0x5b, 0x5d, 0xc3,
	}
	object, text, functions := fixture(t, coff.MachineAMD64, code, functionSpec{"go", 0})
	before := append([]byte(nil), text.Data...)
	seed := int64(123)
	_, err := Apply(context.Background(), object, Options{Seed: &seed})
	if err == nil || !errors.Is(err, ErrUnsupportedInstruction) {
		t.Fatalf("Apply error = %v, want ErrUnsupportedInstruction", err)
	}
	var unsupported *UnsupportedInstructionError
	if !errors.As(err, &unsupported) || unsupported.Function != "go" || unsupported.Offset != 4 || !bytes.Equal(unsupported.Bytes, []byte{0xc5, 0xfc, 0x10, 0x07}) {
		t.Fatalf("typed error = %#v", unsupported)
	}
	if !bytes.Equal(text.Data, before) || functions[0].Value != 0 {
		t.Fatal("failed pass changed the COFF object")
	}
}

func TestApplyRandomFailureIsTransactional(t *testing.T) {
	first := []byte{0x55, 0x53, 0x56, 0x57, 0x89, 0xf3, 0x5f, 0x5e, 0x5b, 0x5d, 0xc3}
	code := append(append([]byte(nil), first...), first...)
	object, text, symbols := fixture(t, coff.MachineI386, code, functionSpec{"first", 0}, functionSpec{"second", uint32(len(first))})
	before := append([]byte(nil), text.Data...)
	// Four registers consume three words per function. Only the first shuffle
	// can complete, but none of its planned bytes may be committed.
	random := bytes.NewReader(make([]byte, 3*4))
	_, err := Apply(context.Background(), object, Options{Random: random})
	if err == nil || !errors.Is(err, io.EOF) {
		t.Fatalf("Apply error = %v, want EOF", err)
	}
	if !bytes.Equal(text.Data, before) || symbols[0].Value != 0 || symbols[1].Value != uint32(len(first)) {
		t.Fatal("random failure changed object")
	}
}

func TestApplyRebasesSymbolsBranchesRelocationsAndUnwind(t *testing.T) {
	seed := int64(123)
	first := []byte{
		0x55, 0x53, 0x56, 0x57, 0x41, 0x54, 0x41, 0x55,
		0x88, 0x1e, // grows from two to four bytes for seed 123
		0xeb, 0x05, // local jump over the relocated call to the first pop
		0xe8, 0x00, 0x00, 0x00, 0x00, // relocated call
		0x41, 0x5d, 0x41, 0x5c, 0x5f, 0x5e, 0x5b, 0x5d, 0xc3,
	}
	second := []byte{0xc3}
	code := append(append([]byte(nil), first...), second...)
	object, text, symbols := fixture(t, coff.MachineAMD64, code, functionSpec{"first", 0}, functionSpec{"second", uint32(len(first))})
	secondSymbol := symbols[1]
	symbols[0].AuxiliaryRecords = [][]byte{make([]byte, 18)}
	binary.LittleEndian.PutUint32(symbols[0].AuxiliaryRecords[0][4:8], uint32(len(first)))
	// A .text relocation after the growing instruction must move with it.
	external := &coff.Symbol{Name: "external", StorageClass: coff.SymbolClassExternal}
	if err := object.AddSymbol(external); err != nil {
		t.Fatal(err)
	}
	relocation := &coff.Relocation{Section: text, VirtualAddress: 13, SymbolName: external.Name, Symbol: external, Type: coff.RelAMD64Rel32}
	text.Relocations = []*coff.Relocation{relocation}

	// Existing RUNTIME_FUNCTION begin/end fields target the .text section
	// symbol. The end addend must follow the moved second function.
	pdata := coff.NewSection(".pdata", make([]byte, 12))
	if err := object.AddSection(pdata); err != nil {
		t.Fatal(err)
	}
	textSymbol := object.GetSymbol(".text")
	binary.LittleEndian.PutUint32(pdata.Data[4:8], uint32(len(first)))
	pdata.Relocations = []*coff.Relocation{
		{Section: pdata, VirtualAddress: 0, SymbolName: textSymbol.Name, Symbol: textSymbol, Type: coff.RelAMD64Addr32NB},
		{Section: pdata, VirtualAddress: 4, SymbolName: textSymbol.Name, Symbol: textSymbol, Type: coff.RelAMD64Addr32NB},
	}

	report, err := Apply(context.Background(), object, Options{Seed: &seed})
	if err != nil {
		t.Fatalf("Apply: %v", err)
	}
	if report.ChangedInstructions != 1 {
		t.Fatalf("report = %#v", report)
	}
	if secondSymbol.Value != uint32(len(first)+2) {
		t.Fatalf("second symbol = %#x, want %#x", secondSymbol.Value, len(first)+2)
	}
	if relocation.VirtualAddress != 15 {
		t.Fatalf("text relocation = %#x, want %#x", relocation.VirtualAddress, 15)
	}
	if got := binary.LittleEndian.Uint32(pdata.Data[4:8]); got != uint32(len(first)+2) {
		t.Fatalf(".pdata end = %#x, want %#x", got, len(first)+2)
	}
	if got := binary.LittleEndian.Uint32(symbols[0].AuxiliaryRecords[0][4:8]); got != uint32(len(first)+2) {
		t.Fatalf("function auxiliary size = %#x, want %#x", got, len(first)+2)
	}
	// The short jump still targets the first pop after the instruction grew.
	if text.Data[12] != 0xeb || text.Data[13] != 5 {
		t.Fatalf("rebased short jump = %x", text.Data[12:14])
	}
}

func TestApplyRelaxesShortBranch(t *testing.T) {
	seed := int64(123)
	code := []byte{0x55, 0x53, 0x56, 0x57, 0x41, 0x54, 0x41, 0x55, 0xeb, 0x7e, 0x88, 0x1e}
	code = append(code, bytes.Repeat([]byte{0x90}, 124)...)
	code = append(code, 0x41, 0x5d, 0x41, 0x5c, 0x5f, 0x5e, 0x5b, 0x5d, 0xc3)
	object, text, _ := fixture(t, coff.MachineAMD64, code, functionSpec{"go", 0})
	if _, err := Apply(context.Background(), object, Options{Seed: &seed}); err != nil {
		t.Fatalf("Apply: %v", err)
	}
	if len(text.Data) != len(code)+5 {
		t.Fatalf("rewritten length = %d, want %d", len(text.Data), len(code)+5)
	}
	if !bytes.Equal(text.Data[8:13], []byte{0xe9, 0x80, 0x00, 0x00, 0x00}) {
		t.Fatalf("relaxed branch = %x, want e980000000", text.Data[8:13])
	}
}

func TestApplyRejectsExistingFramePointerUnwind(t *testing.T) {
	// mov rbp,rsp is deliberately not frozen by upstream; it follows the
	// selected RBP permutation. Existing xdata names RBP in its header and is
	// therefore unsafe, while +unwind generated after this pass is safe.
	code := []byte{
		0x55, 0x53, 0x56, 0x57, 0x41, 0x54, 0x41, 0x55,
		0x48, 0x89, 0xe5,
		0x48, 0x89, 0xf3,
		0x41, 0x5d, 0x41, 0x5c, 0x5f, 0x5e, 0x5b, 0x5d, 0xc3,
	}
	object, text, _ := fixture(t, coff.MachineAMD64, code, functionSpec{"go", 0})
	if err := object.AddSection(coff.NewSection(".xdata", []byte{1, 0, 0, 5})); err != nil {
		t.Fatal(err)
	}
	before := append([]byte(nil), text.Data...)
	seed := int64(123)
	_, err := Apply(context.Background(), object, Options{Seed: &seed})
	if err == nil || !errors.Is(err, ErrUnsupportedUnwind) {
		t.Fatalf("Apply error = %v, want ErrUnsupportedUnwind", err)
	}
	if !bytes.Equal(text.Data, before) {
		t.Fatal("unwind rejection changed .text")
	}
}

func TestApplyConcurrentCalls(t *testing.T) {
	code := []byte{0x55, 0x53, 0x56, 0x57, 0x89, 0xf3, 0x8d, 0x7c, 0x5d, 0x10, 0x01, 0xfe, 0x5f, 0x5e, 0x5b, 0x5d, 0xc3}
	object, _, _ := fixture(t, coff.MachineI386, code, functionSpec{"go", 0})
	seed := int64(123)
	var wait sync.WaitGroup
	errorsByCall := make(chan error, 8)
	for index := 0; index < 8; index++ {
		wait.Add(1)
		go func() {
			defer wait.Done()
			_, err := Apply(context.Background(), object, Options{Seed: &seed})
			errorsByCall <- err
		}()
	}
	wait.Wait()
	close(errorsByCall)
	for err := range errorsByCall {
		if err != nil {
			t.Errorf("concurrent Apply: %v", err)
		}
	}
}

func TestApplyInputValidation(t *testing.T) {
	seed := int64(1)
	if _, err := Apply(nil, &coff.Object{}, Options{}); err == nil {
		t.Fatal("nil context accepted")
	}
	if _, err := Apply(context.Background(), nil, Options{}); err == nil {
		t.Fatal("nil object accepted")
	}
	object, _, _ := fixture(t, coff.MachineI386, []byte{0xc3}, functionSpec{"go", 0})
	if _, err := Apply(context.Background(), object, Options{Seed: &seed, Random: bytes.NewReader(nil)}); err == nil {
		t.Fatal("Seed plus Random accepted")
	}
	cancelled, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := Apply(cancelled, object, Options{}); !errors.Is(err, context.Canceled) {
		t.Fatalf("cancelled error = %v", err)
	}
}

func TestApplyMalformedModels(t *testing.T) {
	tests := []struct {
		name  string
		model func(t *testing.T) *coff.Object
	}{
		{name: "unsupported machine", model: func(t *testing.T) *coff.Object {
			return &coff.Object{Machine: coff.MachineARM64}
		}},
		{name: "nil section", model: func(t *testing.T) *coff.Object {
			return &coff.Object{Machine: coff.MachineI386, Sections: []*coff.Section{nil}}
		}},
		{name: "missing text", model: func(t *testing.T) *coff.Object {
			object, err := coff.NewObject(coff.MachineI386)
			if err != nil {
				t.Fatal(err)
			}
			return object
		}},
		{name: "nil symbol", model: func(t *testing.T) *coff.Object {
			object, _, _ := fixture(t, coff.MachineI386, []byte{0xc3}, functionSpec{"go", 0})
			object.Symbols = append(object.Symbols, nil)
			return object
		}},
		{name: "symbol outside text", model: func(t *testing.T) *coff.Object {
			object, _, symbols := fixture(t, coff.MachineI386, []byte{0xc3}, functionSpec{"go", 0})
			symbols[0].Value = 2
			return object
		}},
		{name: "nil relocation", model: func(t *testing.T) *coff.Object {
			object, text, _ := fixture(t, coff.MachineI386, []byte{0xc3}, functionSpec{"go", 0})
			text.Relocations = []*coff.Relocation{nil}
			return object
		}},
		{name: "unknown relocation", model: func(t *testing.T) *coff.Object {
			object, text, _ := fixture(t, coff.MachineI386, []byte{0xe8, 0, 0, 0, 0, 0xc3}, functionSpec{"go", 0})
			target := &coff.Symbol{Name: "target", StorageClass: coff.SymbolClassExternal}
			if err := object.AddSymbol(target); err != nil {
				t.Fatal(err)
			}
			text.Relocations = []*coff.Relocation{{Section: text, VirtualAddress: 1, Symbol: target, SymbolName: target.Name, Type: 0xffff}}
			return object
		}},
		{name: "foreign relocation symbol", model: func(t *testing.T) *coff.Object {
			object, text, _ := fixture(t, coff.MachineI386, []byte{0xe8, 0, 0, 0, 0, 0xc3}, functionSpec{"go", 0})
			target := &coff.Symbol{Name: "target", StorageClass: coff.SymbolClassExternal}
			text.Relocations = []*coff.Relocation{{Section: text, VirtualAddress: 1, Symbol: target, SymbolName: target.Name, Type: coff.RelI386Rel32}}
			return object
		}},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if _, err := Apply(context.Background(), test.model(t), Options{}); err == nil {
				t.Fatal("Apply accepted malformed model")
			}
		})
	}
}

func TestJavaRandomShuffleVector(t *testing.T) {
	registers := []Register{RBP, RBX, R13, RDI, R12, RSI}
	draws, err := shuffle(registers, newJavaRandom(123))
	if err != nil {
		t.Fatal(err)
	}
	want := []Register{RBX, R12, RSI, RDI, RBP, R13}
	if draws != 5 || !reflect.DeepEqual(registers, want) {
		t.Fatalf("shuffle = %v (%d draws), want %v (5)", registers, draws, want)
	}
}

func TestReaderRandomMatchesJavaPowerOfTwoSelection(t *testing.T) {
	random := readerRandom{reader: bytes.NewReader([]byte{0x20, 0x00, 0x00, 0x00})}
	got, draws, err := random.nextInt(4)
	if err != nil {
		t.Fatal(err)
	}
	// Java uses (bound*next(31))>>31 for powers of two, not bits%bound.
	if got != 1 || draws != 1 {
		t.Fatalf("nextInt(4) = %d (%d draws), want 1 (1)", got, draws)
	}
}

type functionSpec struct {
	name  string
	value uint32
}

func fixture(t testing.TB, machine coff.Machine, code []byte, functions ...functionSpec) (*coff.Object, *coff.Section, []*coff.Symbol) {
	t.Helper()
	object, err := coff.NewObject(machine)
	if err != nil {
		t.Fatal(err)
	}
	text := coff.NewSection(".text", code)
	if err := object.AddSection(text); err != nil {
		t.Fatal(err)
	}
	symbols := make([]*coff.Symbol, 0, len(functions))
	for _, specification := range functions {
		symbol := coff.NewFunctionSymbol(text, specification.name, specification.value)
		if err := object.AddSymbol(symbol); err != nil {
			t.Fatal(err)
		}
		symbols = append(symbols, symbol)
	}
	return object, text, symbols
}
