// SPDX-License-Identifier: GPL-3.0-only

package shatter

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"io"
	"reflect"
	"sync"
	"testing"

	"github.com/sliverarmory/crystal-grotto/internal/coff"
)

func TestApplyDirectUpstreamVectors(t *testing.T) {
	// These exact .text vectors were generated by the unmodified upstream
	// Shatter/Blocks/Jumps/Rebuilder pipeline with Iced 1.21.0 after replacing
	// java.util.Collections.r with new java.util.Random(123).
	seed := int64(123)
	input := []byte{
		0x83, 0xf9, 0x00, 0x74, 0x07,
		0xb8, 0x01, 0x00, 0x00, 0x00, 0xeb, 0x05,
		0xb8, 0x02, 0x00, 0x00, 0x00, 0xc3,
		0x85, 0xd2, 0x75, 0x03, 0x31, 0xc0, 0xc3,
		0xb8, 0x03, 0x00, 0x00, 0x00, 0xc3, 0x90,
	}
	tests := []struct {
		name      string
		machine   coff.Machine
		functions []functionSpec
		want      []byte
	}{
		{
			name:      "x64",
			machine:   coff.MachineAMD64,
			functions: []functionSpec{{"go", 0}, {"helper", 0x12}},
			want: []byte{
				0x83, 0xf9, 0x00, 0x74, 0x02, 0xeb, 0x07,
				0xb8, 0x02, 0x00, 0x00, 0x00, 0xeb, 0x16,
				0xb8, 0x01, 0x00, 0x00, 0x00, 0xeb, 0x0f, 0x90,
				0x85, 0xd2, 0x75, 0x02, 0xeb, 0x09,
				0xb8, 0x03, 0x00, 0x00, 0x00, 0xc3, 0xeb, 0xf1,
				0xc3, 0x31, 0xc0, 0xc3, 0xeb, 0xf2,
			},
		},
		{
			name:      "x86 underscore hash order",
			machine:   coff.MachineI386,
			functions: []functionSpec{{"_go", 0}, {"_helper", 0x12}},
			want: []byte{
				0x83, 0xf9, 0x00, 0x74, 0x02, 0xeb, 0x08,
				0xb8, 0x02, 0x00, 0x00, 0x00, 0xeb, 0x1b, 0x90,
				0xb8, 0x01, 0x00, 0x00, 0x00, 0xeb, 0x13,
				0x85, 0xd2, 0x75, 0x02, 0xeb, 0x08,
				0xb8, 0x03, 0x00, 0x00, 0x00, 0xc3, 0xeb, 0xea,
				0x31, 0xc0, 0xc3, 0xeb, 0xf3, 0xc3,
			},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			object, text, symbols := fixture(t, test.machine, input, test.functions...)
			report, err := Apply(context.Background(), object, Options{Seed: &seed})
			if err != nil {
				t.Fatalf("Apply: %v", err)
			}
			if !bytes.Equal(text.Data, test.want) {
				t.Fatalf(".text = %x\nwant    %x", text.Data, test.want)
			}
			if report.Functions != 2 || report.OriginalBlocks != 8 || report.ShuffledBlocks != 6 || report.RandomDraws != 5 || report.Connectors != 5 || report.HealedJumps != 0 {
				t.Fatalf("report = %#v", report)
			}
			if symbols[0].Value != 0 || symbols[1].Value != 0x16 {
				t.Fatalf("symbols = %#x, %#x; want 0, 0x16", symbols[0].Value, symbols[1].Value)
			}
		})
	}
}

func TestApplyDirectUpstreamNearBranchVector(t *testing.T) {
	// Iced's BlockEncoder shortens source near branches when their shattered
	// targets fit. This probe came from the same upstream setup as the vectors
	// above and prevents accidentally preserving the wider source form.
	input := []byte{
		0x0f, 0x84, 0x06, 0x00, 0x00, 0x00,
		0x90,
		0xe9, 0x01, 0x00, 0x00, 0x00,
		0x90, 0xc3, 0x90, 0x90,
	}
	want := []byte{
		0x74, 0x03, 0x90, 0xeb, 0x05, 0x90,
		0xeb, 0x02, 0x90, 0x90, 0xc3, 0xeb, 0xfb,
	}
	object, text, _ := fixture(t, coff.MachineAMD64, input, functionSpec{"go", 0})
	seed := int64(123)
	if _, err := Apply(context.Background(), object, Options{Seed: &seed}); err != nil {
		t.Fatalf("Apply: %v", err)
	}
	if !bytes.Equal(text.Data, want) {
		t.Fatalf(".text = %x\nwant    %x", text.Data, want)
	}
}

func TestApplyRepairsRelocationsSymbolsAndAuxiliary(t *testing.T) {
	// go has a conditional split plus a relocated external call. helper's body
	// is moved into go's physical region for this seed.
	code := []byte{
		0x75, 0x07, // jne go return
		0xe8, 0, 0, 0, 0, // external relocation
		0xeb, 0x00, // jump to return (healed if adjacent after shuffle)
		0xc3,
		0xe8, 0, 0, 0, 0, 0xc3,
	}
	object, text, symbols := fixture(t, coff.MachineAMD64, code, functionSpec{"go", 0}, functionSpec{"helper", 10})
	external := &coff.Symbol{Name: "external", StorageClass: coff.SymbolClassExternal}
	if err := object.AddSymbol(external); err != nil {
		t.Fatal(err)
	}
	relocGo := &coff.Relocation{Section: text, VirtualAddress: 3, Symbol: external, SymbolName: external.Name, Type: coff.RelAMD64Rel32}
	relocHelper := &coff.Relocation{Section: text, VirtualAddress: 11, Symbol: external, SymbolName: external.Name, Type: coff.RelAMD64Rel32}
	text.Relocations = []*coff.Relocation{relocGo, relocHelper}
	for _, symbol := range symbols {
		symbol.AuxiliaryRecords = [][]byte{make([]byte, 18)}
	}
	seed := int64(1)
	_, err := Apply(context.Background(), object, Options{Seed: &seed})
	if err != nil {
		t.Fatalf("Apply: %v", err)
	}
	if relocGo.VirtualAddress >= uint32(len(text.Data)) || relocHelper.VirtualAddress >= uint32(len(text.Data)) {
		t.Fatalf("relocations not rebased: %#x %#x (len %#x)", relocGo.VirtualAddress, relocHelper.VirtualAddress, len(text.Data))
	}
	if !bytes.Equal(text.Data[relocGo.VirtualAddress:relocGo.VirtualAddress+4], []byte{0, 0, 0, 0}) || !bytes.Equal(text.Data[relocHelper.VirtualAddress:relocHelper.VirtualAddress+4], []byte{0, 0, 0, 0}) {
		t.Fatal("relocation addends changed")
	}
	for _, symbol := range symbols {
		size := binary.LittleEndian.Uint32(symbol.AuxiliaryRecords[0][4:8])
		if size == 0 || uint64(symbol.Value)+uint64(size) > uint64(len(text.Data)) {
			t.Fatalf("function %q auxiliary size = %#x at %#x", symbol.Name, size, symbol.Value)
		}
	}
}

func TestApplyRebasesRIPRelativeLocalLabel(t *testing.T) {
	// lea rax,[rip+2] refers to the global data symbol. A split block is placed
	// between the instruction and that data, requiring a new disp32.
	code := []byte{
		0x75, 0x02, // jne return
		0xc3,
		0x90,
		0x48, 0x8d, 0x05, 0x00, 0x00, 0x00, 0x00,
		0xc3,
	}
	object, text, _ := fixture(t, coff.MachineAMD64, code, functionSpec{"go", 0}, functionSpec{"helper", 4})
	data := coff.NewDataSymbol(text, "value", uint32(len(code)))
	// A symbol at text end is rejected like upstream (there is no instruction
	// on which to declare its label), so point at helper's final RET instead.
	data.Value = uint32(len(code) - 1)
	if err := object.AddSymbol(data); err != nil {
		t.Fatal(err)
	}
	// Rewrite the original displacement from LEA end (11) to RET at 11.
	before := append([]byte(nil), text.Data...)
	seed := int64(2)
	_, err := Apply(context.Background(), object, Options{Seed: &seed})
	if err != nil {
		t.Fatalf("Apply: %v (before %x)", err, before)
	}
	// Capstone must still decode the complete result; the exact target is also
	// represented by the rebased data symbol.
	if data.Value >= uint32(len(text.Data)) {
		t.Fatalf("rebased data symbol = %#x, len=%#x", data.Value, len(text.Data))
	}
	lea := bytes.Index(text.Data, []byte{0x48, 0x8d, 0x05})
	if lea < 0 || lea+7 > len(text.Data) {
		t.Fatalf("rebuilt LEA not found in %x", text.Data)
	}
	displacement := int64(int32(binary.LittleEndian.Uint32(text.Data[lea+3 : lea+7])))
	if target := int64(lea+7) + displacement; target != int64(data.Value) {
		t.Fatalf("RIP-relative target = %#x, want data symbol %#x", target, data.Value)
	}
}

func TestApplyRepairsLocalCallAndNonTextAddend(t *testing.T) {
	code := []byte{
		0xe8, 0x01, 0x00, 0x00, 0x00, 0xc3,
		0x75, 0x01, 0xc3, 0xc3,
	}
	object, text, symbols := fixture(t, coff.MachineAMD64, code, functionSpec{"go", 0}, functionSpec{"helper", 6})
	rdata := coff.NewSection(".rdata", make([]byte, 4))
	if err := object.AddSection(rdata); err != nil {
		t.Fatal(err)
	}
	textSymbol := object.GetSymbol(".text")
	binary.LittleEndian.PutUint32(rdata.Data, symbols[1].Value)
	rdata.Relocations = []*coff.Relocation{{
		Section: rdata, VirtualAddress: 0, Symbol: textSymbol,
		SymbolName: textSymbol.Name, Type: coff.RelAMD64Addr32NB,
	}}
	seed := int64(123)
	if _, err := Apply(context.Background(), object, Options{Seed: &seed}); err != nil {
		t.Fatalf("Apply: %v", err)
	}
	call := bytes.IndexByte(text.Data, 0xe8)
	if call < 0 || call+5 > len(text.Data) {
		t.Fatalf("rebuilt call not found in %x", text.Data)
	}
	displacement := int64(int32(binary.LittleEndian.Uint32(text.Data[call+1 : call+5])))
	if target := int64(call+5) + displacement; target != int64(symbols[1].Value) {
		t.Fatalf("call target = %#x, helper = %#x", target, symbols[1].Value)
	}
	if got := binary.LittleEndian.Uint32(rdata.Data); got != symbols[1].Value {
		t.Fatalf(".rdata .text addend = %#x, helper = %#x", got, symbols[1].Value)
	}
}

func TestApplyHealsAdjacentJump(t *testing.T) {
	object, text, _ := fixture(t, coff.MachineI386, []byte{0xeb, 0x00, 0xc3}, functionSpec{"go", 0})
	seed := int64(1)
	report, err := Apply(context.Background(), object, Options{Seed: &seed})
	if err != nil {
		t.Fatalf("Apply: %v", err)
	}
	if !bytes.Equal(text.Data, []byte{0xc3}) || report.HealedJumps != 1 {
		t.Fatalf("healed output = %x, report=%#v", text.Data, report)
	}
}

func TestHealPreservesBlocksAndRemovesISEDMarker(t *testing.T) {
	code := []byte{
		0x75, 0x03, // jne second RET
		0xeb, 0x00, // ISED +split marker to the next instruction
		0xc3, 0xc3,
	}
	object, text, symbols := fixture(t, coff.MachineI386, code, functionSpec{"go", 0})
	report, err := Heal(context.Background(), object)
	if err != nil {
		t.Fatalf("Heal: %v", err)
	}
	want := []byte{0x75, 0x01, 0xc3, 0xc3}
	if !bytes.Equal(text.Data, want) {
		t.Fatalf(".text = %x, want %x", text.Data, want)
	}
	if report.HealedJumps != 1 || report.ShuffledBlocks != 0 || report.RandomDraws != 0 || report.Connectors != 0 {
		t.Fatalf("report = %#v", report)
	}
	if symbols[0].Value != 0 {
		t.Fatalf("function symbol = %#x", symbols[0].Value)
	}
	if len(report.Assignments) != 0 || len(report.Layouts) != 1 {
		t.Fatalf("unexpected layouts = %#v", report)
	}
}

func TestHealNormalizesMovedTextSectionSymbol(t *testing.T) {
	object, text, symbols := fixture(t, coff.MachineAMD64, []byte{0x90, 0xc3, 0xcc, 0xc3}, functionSpec{"go", 0}, functionSpec{"helper", 2})
	sectionSymbol := object.GetSymbol(".text")
	sectionSymbol.Value = 2 // state produced when +gofirst moved its old chunk
	if _, err := Heal(context.Background(), object); err != nil {
		t.Fatalf("Heal: %v", err)
	}
	if sectionSymbol.Value != 0 {
		t.Fatalf(".text section symbol = %#x, want zero", sectionSymbol.Value)
	}
	if symbols[0].Value != 0 || symbols[1].Value != 2 || !bytes.Equal(text.Data, []byte{0x90, 0xc3, 0xcc, 0xc3}) {
		t.Fatalf("unexpected model after normalization: symbols %#x/%#x, text %x", symbols[0].Value, symbols[1].Value, text.Data)
	}
}

func TestApplyRelaxesShuffledShortBranches(t *testing.T) {
	var code []byte
	for index := 0; index < 80; index++ {
		code = append(code, 0xeb, 0x00, 0x90)
	}
	code = append(code, 0xc3)
	object, text, _ := fixture(t, coff.MachineAMD64, code, functionSpec{"go", 0})
	seed := int64(123)
	report, err := Apply(context.Background(), object, Options{Seed: &seed})
	if err != nil {
		t.Fatalf("Apply: %v", err)
	}
	if report.ExpandedBranches == 0 {
		t.Fatalf("no branches expanded: %#v", report)
	}
	boundaries := map[uint32]struct{}{uint32(len(text.Data)): {}}
	for offset := uint32(0); offset < uint32(len(text.Data)); {
		boundaries[offset] = struct{}{}
		size := uint32(1)
		switch text.Data[offset] {
		case 0xeb:
			size = 2
		case 0xe9:
			size = 5
		}
		offset += size
	}
	for offset := uint32(0); offset < uint32(len(text.Data)); {
		opcode := text.Data[offset]
		size := uint32(1)
		var target int64
		switch opcode {
		case 0xeb:
			size = 2
			target = int64(offset+size) + int64(int8(text.Data[offset+1]))
		case 0xe9:
			size = 5
			target = int64(offset+size) + int64(int32(binary.LittleEndian.Uint32(text.Data[offset+1:offset+5])))
		}
		if opcode == 0xeb || opcode == 0xe9 {
			if target < 0 {
				t.Fatalf("branch %#x targets before .text", offset)
			}
			if _, ok := boundaries[uint32(target)]; !ok {
				t.Fatalf("branch %#x targets non-boundary %#x", offset, target)
			}
		}
		offset += size
	}
}

func TestApplyRejectsLoopOverflowTransactionally(t *testing.T) {
	var code []byte
	code = append(code, 0xe2, 0x00, 0x90)
	for index := 1; index < 100; index++ {
		code = append(code, 0xeb, 0x00, 0x90)
	}
	code = append(code, 0xc3)
	seed := int64(123)
	object, text, _ := fixture(t, coff.MachineI386, code, functionSpec{"go", 0})
	before := append([]byte(nil), text.Data...)
	_, err := Apply(context.Background(), object, Options{Seed: &seed})
	if err == nil || !errors.Is(err, ErrUnsupportedControlFlow) {
		t.Fatalf("Apply error = %v, want loop overflow rejection", err)
	}
	if !bytes.Equal(text.Data, before) {
		t.Fatal("loop overflow changed object")
	}
}

func TestApplyRejectsUnsupportedTransactionally(t *testing.T) {
	tests := []struct {
		name string
		code []byte
		prep func(*coff.Object)
		want error
	}{
		{
			name: "xbegin Iced-only branch",
			code: []byte{0xc7, 0xf8, 0, 0, 0, 0, 0xc3},
			want: ErrUnsupportedControlFlow,
		},
		{
			name: "unwind metadata",
			code: []byte{0xc3},
			prep: func(object *coff.Object) {
				if err := object.AddSection(coff.NewSection(".pdata", make([]byte, 12))); err != nil {
					panic(err)
				}
			},
			want: ErrUnsupportedMetadata,
		},
		{
			name: "line number metadata",
			code: []byte{0xc3},
			prep: func(object *coff.Object) {
				text := object.Sections[0]
				text.PointerToLineNumbers = 1
				text.NumberOfLineNumbers = 1
			},
			want: ErrUnsupportedMetadata,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			object, text, symbols := fixture(t, coff.MachineAMD64, test.code, functionSpec{"go", 0})
			if test.prep != nil {
				test.prep(object)
			}
			before := append([]byte(nil), text.Data...)
			seed := int64(3)
			_, err := Apply(context.Background(), object, Options{Seed: &seed})
			if err == nil || !errors.Is(err, test.want) {
				t.Fatalf("Apply error = %v, want %v", err, test.want)
			}
			if !bytes.Equal(text.Data, before) || symbols[0].Value != 0 {
				t.Fatal("failed pass changed object")
			}
		})
	}
}

func TestApplyRandomFailureIsTransactional(t *testing.T) {
	code := []byte{0x75, 0x01, 0xc3, 0xc3, 0x75, 0x01, 0xc3, 0xc3}
	object, text, symbols := fixture(t, coff.MachineI386, code, functionSpec{"a", 0}, functionSpec{"b", 4})
	before := append([]byte(nil), text.Data...)
	_, err := Apply(context.Background(), object, Options{Random: bytes.NewReader(nil)})
	if err == nil || !errors.Is(err, io.EOF) {
		t.Fatalf("Apply error = %v, want EOF", err)
	}
	if !bytes.Equal(text.Data, before) || symbols[1].Value != 4 {
		t.Fatal("random failure changed object")
	}
}

func TestApplyInputValidation(t *testing.T) {
	seed := int64(1)
	if _, err := Apply(nil, &coff.Object{}, Options{}); err == nil {
		t.Fatal("nil context accepted")
	}
	if _, err := Apply(context.Background(), nil, Options{}); err == nil {
		t.Fatal("nil object accepted")
	}
	object, _, _ := fixture(t, coff.MachineI386, []byte{0xc3}, functionSpec{"go", 0})
	if _, err := Apply(context.Background(), object, Options{Seed: &seed, Random: bytes.NewReader(nil)}); err == nil {
		t.Fatal("Seed plus Random accepted")
	}
	cancelled, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := Apply(cancelled, object, Options{}); !errors.Is(err, context.Canceled) {
		t.Fatalf("cancelled error = %v", err)
	}
}

func TestApplyMalformedModels(t *testing.T) {
	tests := []struct {
		name  string
		model func(t *testing.T) *coff.Object
	}{
		{name: "unsupported machine", model: func(t *testing.T) *coff.Object { return &coff.Object{Machine: coff.MachineARM64} }},
		{name: "missing text", model: func(t *testing.T) *coff.Object {
			object, err := coff.NewObject(coff.MachineI386)
			if err != nil {
				t.Fatal(err)
			}
			return object
		}},
		{name: "nil section", model: func(t *testing.T) *coff.Object {
			return &coff.Object{Machine: coff.MachineI386, Sections: []*coff.Section{nil}}
		}},
		{name: "nil symbol", model: func(t *testing.T) *coff.Object {
			object, _, _ := fixture(t, coff.MachineI386, []byte{0xc3}, functionSpec{"go", 0})
			object.Symbols = append(object.Symbols, nil)
			return object
		}},
		{name: "bytes before first function", model: func(t *testing.T) *coff.Object {
			object, _, _ := fixture(t, coff.MachineI386, []byte{0x90, 0xc3}, functionSpec{"go", 1})
			return object
		}},
		{name: "candidate local symbol", model: func(t *testing.T) *coff.Object {
			object, text, _ := fixture(t, coff.MachineI386, []byte{0x90, 0xc3}, functionSpec{"go", 0})
			if err := object.AddSymbol(&coff.Symbol{Name: "local", Value: 1, Section: text, StorageClass: coff.SymbolClassLabel}); err != nil {
				t.Fatal(err)
			}
			return object
		}},
		{name: "unknown relocation", model: func(t *testing.T) *coff.Object {
			object, text, _ := fixture(t, coff.MachineI386, []byte{0xe8, 0, 0, 0, 0, 0xc3}, functionSpec{"go", 0})
			target := &coff.Symbol{Name: "external", StorageClass: coff.SymbolClassExternal}
			if err := object.AddSymbol(target); err != nil {
				t.Fatal(err)
			}
			text.Relocations = []*coff.Relocation{{Section: text, VirtualAddress: 1, Symbol: target, SymbolName: target.Name, Type: 0xffff}}
			return object
		}},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if _, err := Apply(context.Background(), test.model(t), Options{}); err == nil {
				t.Fatal("Apply accepted malformed model")
			}
		})
	}
}

func TestJavaHashAndRandomVectors(t *testing.T) {
	functions := []*region{{name: "go"}, {name: "helper"}}
	ordered, err := javaHashOrder(functions)
	if err != nil {
		t.Fatal(err)
	}
	if got := []string{ordered[0].name, ordered[1].name}; !reflect.DeepEqual(got, []string{"helper", "go"}) {
		t.Fatalf("hash order = %v", got)
	}
	blocks := []*block{{start: 1}, {start: 2}, {start: 3}, {start: 4}, {start: 5}, {start: 6}}
	draws, err := shuffleBlocks(blocks, newJavaRandom(123))
	if err != nil {
		t.Fatal(err)
	}
	var got []uint32
	for _, next := range blocks {
		got = append(got, next.start)
	}
	if draws != 5 || !reflect.DeepEqual(got, []uint32{2, 5, 6, 4, 1, 3}) {
		t.Fatalf("shuffle = %v (%d draws)", got, draws)
	}
}

func TestApplyConcurrentIndependentObjects(t *testing.T) {
	seed := int64(123)
	code := []byte{0x75, 0x01, 0xc3, 0xc3, 0x75, 0x01, 0xc3, 0xc3}
	var wait sync.WaitGroup
	errs := make(chan error, 8)
	for index := 0; index < 8; index++ {
		wait.Add(1)
		go func() {
			defer wait.Done()
			object, _, _ := fixture(t, coff.MachineI386, code, functionSpec{"a", 0}, functionSpec{"b", 4})
			_, err := Apply(context.Background(), object, Options{Seed: &seed})
			errs <- err
		}()
	}
	wait.Wait()
	close(errs)
	for err := range errs {
		if err != nil {
			t.Errorf("Apply: %v", err)
		}
	}
}

type functionSpec struct {
	name  string
	value uint32
}

func fixture(t testing.TB, machine coff.Machine, code []byte, functions ...functionSpec) (*coff.Object, *coff.Section, []*coff.Symbol) {
	t.Helper()
	object, err := coff.NewObject(machine)
	if err != nil {
		t.Fatal(err)
	}
	text := coff.NewSection(".text", code)
	if err := object.AddSection(text); err != nil {
		t.Fatal(err)
	}
	symbols := make([]*coff.Symbol, 0, len(functions))
	for _, specification := range functions {
		symbol := coff.NewFunctionSymbol(text, specification.name, specification.value)
		if err := object.AddSymbol(symbol); err != nil {
			t.Fatal(err)
		}
		symbols = append(symbols, symbol)
	}
	return object, text, symbols
}
